---
- name: Install common packages.
  apt:
    name:
      - curl
      - git
      - python3
      - software-properties-common
      - tmux
      - tree
      - unzip
      - vim
      - sshpass
    state: present

- name: Setup Timezone.
  timezone:
    name: "{{ common_timezone }}"
