---
- name: Check open ports
  hosts: all
  become: yes
  gather_facts: no
  serial: 3

  vars:
    - output_dir: /var/opt/check-ports

  tasks:
    - name: Set timestamp.
      shell: 'date +%Y%m%d-%H%M%S'
      register: run_timestamp
      changed_when: false

    - name: Check for open ports.
      shell:
        cmd: netstat -tupan | egrep 'LISTEN|ESTABLISHED'
        warn: false
      register: open_ports
      changed_when: false

    - name: Ensure Output Dir exists.
      local_action:
        module: ansible.builtin.file
        path: "{{ output_dir }}"
        state: directory
        mode: 0655

    - name: Register open ports.
      local_action:
        module: ansible.builtin.copy
        content: "{{ open_ports.stdout }}"
        dest: "{{ output_dir }}/{{ inventory_hostname }}-{{ run_timestamp.stdout }}.csv"
        mode: 0644
      when: open_ports.stdout != ''
